name: "yolo_infer_vehicle_det"
platform: "onnxruntime_onnx"
max_batch_size: 6
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3, -1, -1]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [84,-1]
  }
]
instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]

